### ISSUE TITLE
Jak to uruchomić?

### ISSUE THREAD

**Issue by wir19** [jakubfi/emelf#3]
Powiedzmy , że skompilowałem sobie program z examples.
```
./emelfread -a loops.out
Cannot read EMELF contents.
```

co robie nie tak? Jak zobaczyć nagłówek, jak dowiedzieć się ile patrzebuje zasobów by uruchomic taki program. System dozuje zasoby i musze wiedzieć ile ich oddać użytkownikowi którego tworzę

**Comment by jakubfi** [comment]
Aby emelfread mógł zadziałać, obiekt binarny musi zostać zbudowany emas-em z opcją "-O emelf".
Tak czy inaczej, emelf został zarzucony i zostanie w przyszłości usunięty jako zależność innych narzędzi. Poprawki nie będą wprowadzane.

**Comment by wir19** [comment]
Aha
